t01_send:
	python tutorial01_send.py
t01_recv:
	python tutorial01_receive.py
t02_new_task:
	python tutorial02_new_task.py first.
	python tutorial02_new_task.py second..
	python tutorial02_new_task.py three...
	python tutorial02_new_task.py four....
	python tutorial02_new_task.py five.....
	python tutorial02_new_task.py six......
	python tutorial02_new_task.py seven.......
t02_new_task_persist:
	python tutorial02_new_task_persist.py first.
	python tutorial02_new_task_persist.py second..
	python tutorial02_new_task_persist.py three...
	python tutorial02_new_task_persist.py four....
	python tutorial02_new_task_persist.py five.....
	python tutorial02_new_task_persist.py six......
	python tutorial02_new_task_persist.py seven.......
t02_worker:
	python tutorial02_worker.py
t02_worker_ack:
	python tutorial02_worker_ack.py
t02_worker_persist:
	python tutorial02_worker_persist.py
t03_send:
	python tutorial03_send.py
t03_receive:
	python tutorial03_receive.py
t04_send:
	python tutorial04_send.py
t04_error:
	python tutorial04_error.py
t04_info:
	python tutorial04_info.py
t05_send:
	python tutorial05_send.py
t05_error:
	python tutorial05_error.py
t05_info:
	python tutorial05_info.py